name: Reports

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 6,18 * * *'
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TRINO_VERSION: 370
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y aha
      - name: Start Trino
        run: |
          CONTAINER_ID=$(docker run \
            -v $(pwd)/catalog/hive.properties:/etc/trino/catalog/hive.properties \
            -v $(pwd)/hive-cache:/opt/hive-cache \
            -e AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY \
            -e AWS_REGION \
            -p 8080:8080 \
            --name trino \
            -d \
            trinodb/trino:$TRINO_VERSION)
          SERVER_IP=$(docker inspect --format '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$CONTAINER_ID")
          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
          echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV
          # give it some time to start up
          sleep 30
          docker logs trino
      - name: Execute queries
        run: |
          ./bin/reports.sh reports/ci-cd/index.md "Trino CI/CD Reports" sql/ci-cd/{health,runs-queue-time-per-day,runs-duration-per-day,jobs-duration,flaky-tests}.sql
          ./bin/reports.sh reports/pr/index.md "Trino PR Reports" sql/pr/{stale-prs}.sql
      - name: Commit report
        run: |
          git config --global user.name 'Jan Was'
          git config --global user.email 'nineinchnick@users.noreply.github.com'
          git add --all reports/
          git commit -m "Automated report"
          git push
